[tools]
node = 'lts'

python = ['3.14.0']
pipx = 'latest'
uv = 'latest'

go = '1.25.3'
bun = '1.3.1'

"rust" = { version = "1.91.1" }
# "zig" =  { version = "0.16.0" }
"java" = { version = "openjdk-17" }
